### ISSUE TITLE
cooldown error

### ISSUE THREAD

**Issue by Dark32** [Dark32/RPchat2#37]
Поддержка групповых значений задержек/кулдован
Работает, только при указании "cooldown: 20" настройки для групп игнорятся. Лучше было бы если данная настройка отвечала за кулдаун по-умолчанию, либо вообще убрать, т.к. без надобности - внес в

```
    groups:
        default:
            default: true
            cooldown: 20
```

и всё.
